### PR TITLE
Refactored

### PR DESCRIPTION
**Pull request by cspeterson**

### CODE REVIEW

**Comment by cspeterson** [comment]
ping

**Comment by cspeterson** [comment]
@bepstein

**Comment by bepstein** [comment]
Not really sure what I'm supposed to do here.  Maybe we can look at it together?

**Comment by cspeterson** [comment]
yes

**Comment by cspeterson** [comment]
ping

**Comment by bepstein** [comment]
I think this is merged now... 

-- 
Brian Epstein ***@***.***> (he/him) +1 609-734-8179 
Manager, Network and Security, CISO Institute for Advanced Study 
Key fingerprint = 5CD3 1511 CFCD 9388 1A53 7A45 3137 D4CC C418 A386

**Pull request merged**
